mysql and family: requires ld64 on Tiger
Without ld64, mysql fails with a "multiple definitions of symbol"
error: https://gist.github.com/shirleyallan/6275208