Symbol#to_proc: fix with arrays of arrays
Previously, with nested arrays, the Symbol#to_proc would iterate over
the first item in the nested array instead of the array itself, e.g.:

[[1,2], [3,4]].map(&:first) #=>
	NoMethodError: undefined method `first' for 1:Fixnum