Fix python3 postinstall
Postinstall was failing with these errors, which caused (perhaps among other problems?) easy_install and pip3 to not be linked & added to PATH properly.

`vivtop-g4:~/Desktop vivlim$ brew postinstall python3
Error: wrong number of arguments (2 for 1)
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Formula/python3.rb:220:in '[]'
/usr/local/Library/Formula/python3.rb:220:in 'post_install'
/usr/local/Library/Homebrew/formula.rb:765:in 'run_post_install'
/usr/local/Library/Homebrew/cmd/postinstall.rb:3:in 'postinstall'
/usr/local/Library/Homebrew/cmd/postinstall.rb:3:in 'each'
/usr/local/Library/Homebrew/cmd/postinstall.rb:3:in 'postinstall'
/usr/local/Library/brew.rb:143:in 'send'
/usr/local/Library/brew.rb:143
vivtop-g4:~/Desktop vivlim$`