libffi 3.4.7
Make universal builds optional, fixes build on 10.6 & up where we
build in 64-bit mode. Otherwise the build fails:
Undefined symbols for architecture i386:
  "_ffi_prep_cif_machdep", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_closure_loc", referenced from:
      _ffi_prep_closure in prep_cif.o
  "_ffi_prep_raw_closure_loc", referenced from:
      _ffi_prep_raw_closure in raw_api.o
ld: symbol(s) not found for architecture i386

It was originally introduced to help install the ffi gem using
ruby 1.8.7 which shipped with Snow Leopard, in commit 2bcc4fccee3c8e8820448b65d2a3e243032e2ec5