libtorrent: fix building with gcc-7.3.0
Instrumentation generates the following missing symbols on g4:
undefined reference to __sync_add_and_fetch_8

See also https://github.com/rakshasa/rtorrent/issues/156.